### ISSUE TITLE
[BUG] Spark driver logs not accessible via dashboard

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#1435]
**Describe the bug**

Cannot view Kubernetes driver logs in the dashboard. 

**Expected behavior**

Driver logs are accessible in the Kubernetes dashboard.

**[Optional] Additional context**
***To Reproduce***
1. Configure the sandbox to run spark jobs as per the [docs](https://docs.flyte.org/projects/cookbook/en/latest/auto/integrations/kubernetes/k8s_spark/index.html)
2. Run a spark job in the sandbox
3. View the logs in the console

***Screenshots***

The driver logs URL is http://localhost:30082/#!/log/flyteexamples-development/uymeomum4w-n0-0-driver/pod?namespace=flyteexamples-development

![Kapture 2021-09-05 at 16 33 21](https://user-images.githubusercontent.com/125105/132117878-2b09577e-4bfc-4ee1-bded-6741c6761241.gif)

**Comment by evalsocket** [comment]
@tekumara this because of our recent changes. We migrated sandbox from kustomize to helm. It helm values issue. I will create a patch for that. For mean time you change k8s dashboard cluster-role-binding to cluster-admin and it will unblock you

**Comment by evalsocket** [comment]
@tekumara It is fixed in the master branch and a fix will be available in the next patch release.

**Comment by tekumara** [comment]
Thanks @evalsocket I've tested this and I have fewer auth issues but the logs still don't appear.

The link goes to 

http://localhost:30082/#!/log/flyteexamples-development/f118d43a570c34e84a32-n0-0-driver/pod?namespace=flyteexamples-development

instead of

http://localhost:30082/#/log/flyteexamples-development/f118d43a570c34e84a32-n0-0-driver/pod?namespace=flyteexamples-development
