### ISSUE TITLE
[BUG] Attempts are not sorted in UI

### ISSUE THREAD

**Issue by fg91** [flyteorg/flyte#4504]
### Describe the bug

The list of attempts of a task in flyteconsole are not sorted alphabetically.

### Expected behavior

It would make sense to do so though as otherwise, when the number of attempts is large, it can be annoying to find a specific one.

### Additional context to reproduce

Running the 1.10 release of the helm chart.

### Screenshots

<img width="284" alt="Screenshot 2023-11-30 at 14 43 38" src="https://github.com/flyteorg/flyte/assets/36511035/97c33450-97f2-486f-b405-6098d299c9c5">

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by fg91** [comment]
> "Hello 👋, this issue has been inactive for over 90 days. To help maintain a clean and focused backlog, we'll be marking this issue as stale and will close the issue if we detect no activity in the next 7 days. Thank you for your contribution and understanding! 🙏"

Not fixed yet.

**Comment by kumare3** [comment]
This is fixed in v2. Completely overhauled model

**Comment by fg91** [comment]
Still an issue in v1 flyteconsole, reopening for visibility :)
